CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id VARCHAR(64) NOT NULL UNIQUE,
  account_id VARCHAR(64) NOT NULL,
  type VARCHAR(16) NOT NULL CHECK (type IN ('CREDIT','DEBIT')),
  amount DECIMAL(19,4) NOT NULL CHECK (amount > 0),
  currency VARCHAR(8) NOT NULL,
  event_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
  metadata VARCHAR(2000),
  received_at TIMESTAMP WITH TIME ZONE NOT NULL,
  applied_to_account BOOLEAN NOT NULL DEFAULT FALSE,
  retry_count INT NOT NULL DEFAULT 0,
  last_retry_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_events_account_ts ON events(account_id, event_timestamp);
CREATE INDEX IF NOT EXISTS idx_events_pending ON events(applied_to_account, retry_count);
